//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5BLibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booksdetail
    {
        public int booksdetailsid { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public int publishyear { get; set; }
        public string category { get; set; }
        public string isbn { get; set; }
        public int quantity { get; set; }
    }
}
