//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5BLibraryManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returndetail
    {
        public int Returndetailsid { get; set; }
        public int loandetailsid { get; set; }
        public System.DateTime returndate { get; set; }
    
        public virtual Loandetail Loandetail { get; set; }
    }
}
