//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team5BLibraryManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SA47Team05BESNETLMSEntities : DbContext
    {
        public SA47Team05BESNETLMSEntities()
            : base("name=SA47Team05BESNETLMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Booksdetail> Booksdetails { get; set; }
        public virtual DbSet<Loandetail> Loandetails { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Returndetail> Returndetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
